version: "3"

services:
  app:
    container_name: "app"
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    expose:
      - 3000
    networks:
      - rede-interna-entre-apps
    depends_on:
      - db
  proxy:
    container_name: "nginx"
    build:
      context: .
      dockerfile: "Dockerfile.proxy"
    ports:
      - "8080:80"
    networks:
      - rede-interna-entre-apps
    depends_on:
      - db
  db:
    container_name: "db"
    image: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - rede-interna-entre-apps

networks:
  rede-interna-entre-apps:
    driver: bridge
